### ISSUE TITLE
cannot translate news item using fluent

### ISSUE THREAD

**Issue by wernerkrauss** [Firesphere/silverstripe-newsmodule#143]
I'm currently using fluent (https://github.com/tractorcow/silverstripe-fluent) to translate my site, but news items are not translated, as fluent extension wants to update the cms fields.

why is field generation of news item done somewhere in an extension?

See fluent docs: https://github.com/tractorcow/silverstripe-fluent/blob/3.1/docs/en/dataobjects.md

**Comment by Firesphere** [comment]
Field generation is done in extensions, to unclutter the classes from all the extras and have a clearer view of what's happening at the creation of the fields.

By putting it apart, I didn't have in mind the fluent translation. I'll have to have a look at it to see if there's anything possible.

**Comment by wernerkrauss** [comment]
generating it by calling "updateCMSFields" is very contra productive, cause you cannot determine the order of any extensions to this dataobject. In my case fluent did update the scaffolded fields, and after that news extension threw everything away and generated from scratch.

At least getting the stuff done in getCMSFields (you can call all this helper functions) eases it, but we'd have to call $this->extend('updateCMSFields') again in News DO.

I did a hacky fix that works for me now (https://github.com/wernerkrauss/silverstripe-newsmodule/commit/6e524238e8bdfb82266510044bcade920c989f2e), getting Field geration back to a more standard compliant way would be really great.

Why not use the form scaffolder and move the already generated fields to the right tabs? There is also a method for reordering a fieldlist (http://api.silverstripe.org/3.1/class-FieldList.html#_changeFieldOrder). I bet this could also improve performance ;)

**Comment by Firesphere** [comment]
I know my solution isn't the most elegant, but it was becoming such a big mess, that I wanted to clear it out and start from scratch.

Your hacky method isn't that bad. But the problem is, I want fields rendered based on the config, not just reorder them. I'll have a look this weekend.

Your argument is very valid :)

**Comment by wernerkrauss** [comment]
Searching around in fluent i found a way to unclutter the code using editor folds: 
https://github.com/tractorcow/silverstripe-fluent/blob/3.1/code/extensions/FluentExtension.php#L11

Also possible with PHPstorm / IDEA:
https://www.jetbrains.com/idea/help/folding-custom-regions-with-line-comments.html

maybe a way to sort / structure the code a bit better.

**Comment by Firesphere** [comment]
Sorry for the delay.

This is still on the list, but I've been quite sick last week, and busy before that, so, in short. I'm lacking time to work on issues at the moment :'(

**Comment by Firesphere** [comment]
Pushed your changes to master by cherry-picking. I'm still not sure about the date thing though ;)

**Comment by Firesphere** [comment]
Hmmm, I noticed your change has a lot of extra plusses! Now, UpdateCMSFields on extensions on News work better!
