### ISSUE TITLE
Caching issue

### ISSUE THREAD

**Issue by Legin76** [Firesphere/silverstripe-newsmodule#147]
I've got a strange issue where the news page / archive pages  is not working correctly.

If I clear the cache the first news page to load is used for all news pages. For example if I clear the cache, then load /news/archive/2015/March, I will get the March articles then if I go to  /news it will still only list the March articles. The cached result with the only the March articles shows on all news list pages, even other months or years. In order to show the full list again I need to clear the cache and make sure that / news is the first news page to load but then all the archive pages have the full list of all articles.

I've updated it to the latest version of silverstripe-newsmodule and the framework / cms is 3.1.5

**Comment by Firesphere** [comment]
Hmmm, sounds like I left a bug in the Archive. I'll have to look at that.

Best you can do, is (copy the templates to your themes dir and) remove the caching tags in your themesdir's NewsHolderPage types. It's not a big performance hit to not use caching.

**Comment by Legin76** [comment]
That's fixed it for now.. Thanks...

**Comment by Firesphere** [comment]
Thanks for re-opening. It's indeed still a bug I'll need to fix. ;)

**Comment by Firesphere** [comment]
This might need to go into the docs. The given templates are examples, they're not strict.

**Comment by Legin76** [comment]
I think it's down to an update to silverstripe. It worked when we first setup the site.

**Comment by Firesphere** [comment]
I should remove the caching completely. Caching should be a user's choice, not mine.

**Comment by Legin76** [comment]
You could just comment it out from the templates, with a note saying that it may not work.

**Comment by Firesphere** [comment]
A pull request is very welcome.
I don't have the time to actively fully maintain this module at the moment, I only update if it's really, really necessarry.
This time will come back again, where I will finally finish handling all the issues etc. but for now I prefer a pull request.
@wernerkrauss You were talking about a few other things in the given templates. We talked about this on IRC. Feel very free to create a pull request. I'll review and merge in the code is agreed. I'm just having a few too few hours in a day last couple of months :)

**Comment by Firesphere** [comment]
For now, develop branch has the caching-tags removed.
