### ISSUE TITLE
Errors in en.yml

### ISSUE THREAD

**Issue by Legin76** [Firesphere/silverstripe-newsmodule#148]
I've updated a few lines in en.yml as there was some Dutch 

Line 68: PLURALNAME: Nieuwsberichten
to: PLURALNAME: 'News Articles'
I've also changed the lines 58 down to 67 to say news articles rather than news items.

NEWSITEMTYPE: News article
NEWSTYPE: 'Type of article'
PERMISSION_CREATE_DESCRIPTION: 'Create news articles'
PERMISSION_CREATE_HELP: 'Permission required to create new news articles.'
PERMISSION_DELETE_DESCRIPTION: 'Delete news articles'
PERMISSION_DELETE_HELP: 'Permission required to delete existing articles.'
PERMISSION_EDIT_DESCRIPTION: 'Edit news articles'
PERMISSION_EDIT_HELP: 'Permission required to edit existing news articles.'
PERMISSION_VIEW_DESCRIPTION: 'View news articles'
PERMISSION_VIEW_HELP: 'Permission required to view existing news articles.'

**Comment by Firesphere** [comment]
Best is to signup to Transifex. This project is translated via Transifex, once you signed up, I can add you to the translate-team so you can add/edit translations :)

But I'll keep it in mind.
At this moment I'm a bit too busy to actively maintain this module. I'm just keeping it up to date if needed.

**Comment by Firesphere** [comment]
Marked as invalid. Translations should be managed via Transifex.

Agreed on the updates for the translation though.
