### ISSUE TITLE
composer notice

### ISSUE THREAD

**Issue by wernerkrauss** [Firesphere/silverstripe-newsmodule#149]
Package ajshort/silverstripe-gridfieldextensions is abandoned, you should avoid
using it. Use silverstripe-australia/gridfieldextensions instead.

**Comment by wernerkrauss** [comment]
just seen it's already fixed @743de35327c47728e50721bf24d3837b3e40987b, sorry for the inconvenience...

**Comment by Firesphere** [comment]
Heh, no problem, yes, I fixed that long ago. And I have a long list of issues I have to look at.... :|
