### ISSUE TITLE
Subsite compatibility

### ISSUE THREAD

**Issue by Firesphere** [Firesphere/silverstripe-newsmodule#151]
When using Subsite module, the list and editing of items suddenly seem to disappear.

**Comment by wernerkrauss** [comment]
The ModelAdmin for managing news?

You need to apply https://github.com/silverstripe/silverstripe-subsites/blob/master/code/extensions/SubsiteMenuExtension.php to your modeladmin if you want to show it in left nav.

**Comment by Firesphere** [comment]
Nope, not it. It's giving an empty list of items with Subsite enabled. So it's something "bigger" than just enabling it in the nav.
I have utterly no clue where to look yet though.

**Comment by wernerkrauss** [comment]
Subsites alters the dataquery if you apply the subsites extension, e.g. for SiteTree.

`Subsite::disable_subsite_filter(true);` disables this filter. No sexy ORM yet afaik.

https://github.com/silverstripe/silverstripe-subsites/blob/master/code/model/Subsite.php#L221

**Comment by Firesphere** [comment]
I wish that was it, still.... nope, I still randomly get an empty list, depending on the server I'm looking at. It's a seriously odd issue.
Send me an e-mail if you want to see what's wrong (I trust you won't wreck my website ;) ). It's since I installed Subsites, this happened. I've been testing, but everything works fine on my Vagrant, but bugs out on the live website.

**Comment by Firesphere** [comment]
Partially resolved in latest master.

**Comment by Firesphere** [comment]
Yep, resolved by manually setting the joins. Sad but true.
