### ISSUE TITLE
Links generated for news items are invalid

### ISSUE THREAD

**Issue by LoveDuckie** [Firesphere/silverstripe-newsmodule#157]
When adding a new news item, I've noticed that the link or URL that is generated is in fact valid. It can be recitified with manual input, but the read only link that is displayed through the CMS frontend is actually invalid.

View the screenshot for more information.

![image](https://cloud.githubusercontent.com/assets/692378/8891356/fa44b736-331d-11e5-93e7-0cbc48ecbbde.png)

**Comment by Firesphere** [comment]
Hmmm, seems I have broken this in this commit: https://github.com/Firesphere/silverstripe-newsmodule/commit/57922ec7e1659bf573f7772cdcf3a6fb5c93f9a4
I'll see if it's indeed the case and fix it this week.

**Comment by LoveDuckie** [comment]
Cool. :)

Thanks again for this great module.

**Comment by Firesphere** [comment]
I won't be able to make it this week. Too much work, too little time. A PR is very welcome.

**Comment by LoveDuckie** [comment]
I can take a look at it. Currently working on a new silver stripe website at the moment that uses your module.

-------- Original message --------

**Comment by Firesphere** [comment]
Resolved in https://github.com/Firesphere/silverstripe-newsmodule/commit/09dc284ad67411789c8766be3aba56a1b226892f
