### ISSUE TITLE
nothing is saved into `NewsHolderPage_Newsitems`

### ISSUE THREAD

**Issue by dacar** [Firesphere/silverstripe-newsmodule#168]
Hi, i am trying to youse silverstripe-newsmodule. Installation worked fine with SS 3.2.2. I did the configs, added a NewsHolder Page and added some news. Everything saved successfully. But no news are showen in the frontend. After having a look into the DB i recognized that `NewsHolderPage_Newsitems`. is empty. After adding the ID's manually into the database the news are listed in the frontend. The following ClassNames are written into SiteTree: 'SiteTree','Page','BildergalerieHolder','ReferenzenHolder','Referenzen','Home','NewsHolderPage','ErrorPage','RedirectorPage','VirtualPage','UserDefinedForm'.

Any idea where to look at? Thanks for sharing and your help.

**Comment by Firesphere** [comment]
Hi Carsten,

I've been getting e-mails about this (I get noticed when something goes 
wrong on my demo site), but haven't had the time to have a good look at 
it yet.

I'm assuming, there's something wrong with finding the first page, for 
when there's none set via the CMS (This option appears when there are 
multiple newsholderpages).

I will try to have a look at it this weekend. It's the fastest I can.

Regards,
Simon

**Comment by dacar** [comment]
Is it a problem with translatable? I can't see it???
NewsCMSExtension:

	private function multipleNewsHolderPages()
	{
		$enabled = false;
		// If we have translations, disable translation filter to get all pages.
		if (class_exists('Translatable')) {
			$enabled = Translatable::disable_locale_filter();
		}
		$pages = Versioned::get_by_stage('NewsHolderPage', 'Live');
		// Only add the page-selection if there are multiple. Otherwise handled by onBeforeWrite();
		if ($pages->count() > 1) {
			$pagelist = array();
			if (class_exists('Translatable')) {
				foreach ($pages as $page) {
					$pagelist['Root.Main'][$page->ID] = $page->Title . ' ' . $page->Locale;
				}
			} else {
				$pagelist = $pages->map('ID', 'Title')->toArray();
			}
			$this->field_list['Root.Main'][1] = ListboxField::create('NewsHolderPages', $this->owner->fieldLabel('NewsHolderPages'), $pagelist);
			$this->field_list['Root.Main'][1]->setMultiple(true);
		}
		if ($enabled) {
			Translatable::enable_locale_filter();
		}
	}

**Comment by Firesphere** [comment]
Ah, you're using translatable? In that case I need to have a look at that.

**Comment by dacar** [comment]
Yes, i do.

**Comment by Firesphere** [comment]
Thanks, I didn't realize that.

I'll do some more investigation. I am guessing it has something to do 
with translatable changes which I didn't keep up with.

I'll try to have a look this evening or tomorrow.

**Comment by dacar** [comment]
Hi Firesphere, have you found a solution for the problem? Greetings, Carsten.

**Comment by Firesphere** [comment]
Hey @dacar, I haven't yet been able to even reproduce the problem. Could you be so kind as to send me your composer.json and a little background as how many languages and holderpages you have?

**Comment by dacar** [comment]
Hi @Firesphere i currently use 3 languages (default = DE, EN_US and ZH) and one Holder Page.

Here is my composer.json:

{
	"name": "silverstripe/installer",
	"description": "The SilverStripe Framework Installer",
	"require": {
		"php": ">=5.3.3",
		"silverstripe/cms": "3.2.1",
		"silverstripe/framework": "3.2.1",
		"silverstripe/reports": "3.2.1",
		"silverstripe/siteconfig": "3.2.1",
		"silverstripe-themes/simple": "3.1.*"
	},
	"require-dev": {
		"phpunit/PHPUnit": "~3.7"
	},
	"config": {
		"process-timeout": 600
	},
	"prefer-stable": true,
	"minimum-stability": "dev"
}

**Comment by Firesphere** [comment]
Hi Carsten,

I see you just use the installer.

Do you mean you have one holder page per language, or just one in total? 
Because that might be the problem (it shouldn't, but as I haven't had 
much time to stay updated with Translatable... you know how it goes)

What other modules, besides news and translatable do you have?
I think it would be best if you'd go full composer. I'll gladly help 
you, if you tell me the modules you have?
To speed my support, you can e-mail me a sample database to 
github@casa-laguna.net, if you want?

**Comment by dacar** [comment]
@Firesphere Thanks, Just sent you the Dump via email.
Modules:

googlesitemaps
gridfieldpaginatorwithshowall
optionaltreedropdownfield
reports
searchable
silverstripe-display-logic
silverstripe-gridfieldextensions
silverstripe-newsmodule
silverstripe-seo-master
SortableGridField
staticpublisher
translatable and 
userforms

**Comment by Firesphere** [comment]
Hey Carsten, I'll get a shot at what's going wrong this weekend. No 
promises, but I do have a few days extra to test :)

I'll get back to you if I find something. Dump is received correctly and 
I replied to it :)

**Comment by Firesphere** [comment]
@dacar,
I've found the issue. The problem is, there's only one NewsHolderPage.
I have assumed, that in case of multiple languages via Translatable, every language would have it's own HolderPage. I'll update my faulty assumption with the correct somewhere this weekend.

**Comment by Firesphere** [comment]
@dacar I have pushed a new version, 5.6.5. This should resolve your issue.
Please reopen this issue if it doesn't?

**Comment by dacar** [comment]
Hi Firesphere, thanks a lot for your help.
